events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Включаем gzip для текстовых и часто используемых форматов
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        listen 80;

        server_name _;

        root /usr/share/nginx/html;

        # Кеш для .sgf файлов (1 день)
        location ~* \.sgf$ {
            add_header Cache-Control "public, max-age=86400";
            add_header Access-Control-Allow-Origin *;
            try_files $uri =404;
        }

        # Для всех остальных файлов
        location / {
            autoindex on;           
            autoindex_exact_size off;
            autoindex_localtime on;
        }
    }
}
